{{ config(
    materialized="table"
) }}

select 
    ARENA_CITY::VARCHAR as ARENA_CITY
    ,ARENA_COUNTRY::VARCHAR as ARENA_COUNTRY
    ,ARENA_NAME::VARCHAR as ARENA_NAME
    ,ARENA_STATE::VARCHAR as ARENA_STATE
    ,TRY_TO_NUMBER(DATE_DURATION) as DATE_DURATION
    ,TRY_TO_TIMESTAMP(DATE_END) as DATE_END
    ,TRY_TO_TIMESTAMP(DATE_START) as DATE_START
    ,TRY_TO_NUMBER(ID) as ID
    ,LEADCHANGES::VARCHAR as LEADCHANGES
    ,LEAGUE::VARCHAR as LEAGUE
    ,NUGGET::VARCHAR as NUGGET
    ,OFFICIALS::VARCHAR as OFFICIALS
    ,TRY_TO_NUMBER(PERIODS_CURRENT) as PERIODS_CURRENT
    ,TRY_TO_BOOLEAN(PERIODS_ENDOFPERIOD) as PERIODS_ENDOFPERIOD
    ,TRY_TO_NUMBER(PERIODS_TOTAL) as PERIODS_TOTAL
    ,SCORES_HOME_LINESCORE as HOME_LINESCORE
    ,{{ get_qt_scores('SCORES_HOME_LINESCORE', "HOME") }}
    ,TRY_TO_NUMBER(SCORES_HOME_LOSS) as HOME_LOSS
    ,TRY_TO_NUMBER(SCORES_HOME_POINTS) as HOME_POINTS
    ,TRY_TO_NUMBER(SCORES_HOME_SERIES_LOSS) as HOME_SERIES_LOSS
    ,TRY_TO_NUMBER(SCORES_HOME_SERIES_WIN) as HOME_SERIES_WIN
    ,TRY_TO_NUMBER(SCORES_HOME_WIN) as HOME_WIN
    ,SCORES_VISITORS_LINESCORE as VISITORS_LINESCORE 
    ,{{ get_qt_scores('SCORES_VISITORS_LINESCORE', "VISITORS") }}
    ,TRY_TO_NUMBER(SCORES_VISITORS_LOSS) as VISITORS_LOSS
    ,TRY_TO_NUMBER(SCORES_VISITORS_POINTS) as VISITORS_POINTS
    ,TRY_TO_NUMBER(SCORES_VISITORS_SERIES_LOSS) as VISITORS_SERIES_LOSS
    ,TRY_TO_NUMBER(SCORES_VISITORS_SERIES_WIN) as VISITORS_SERIES_WIN
    ,TRY_TO_NUMBER(SCORES_VISITORS_WIN) as VISITORS_WIN
    ,TRY_TO_NUMBER(SEASON) as SEASON
    ,TRY_TO_NUMBER(STAGE) as STAGE
    ,STATUS_CLOCK::VARCHAR as STATUS_CLOCK
    ,TRY_TO_BOOLEAN(STATUS_HALFTIME) as STATUS_HALFTIME
    ,STATUS_LONG::VARCHAR as STATUS_LONG
    ,TRY_TO_NUMBER(STATUS_SHORT) as STATUS_SHORT
    ,TRY_TO_TIMESTAMP(SYNC_TIME) as SYNC_TIME
    ,TEAMS_HOME_CODE::VARCHAR as TEAMS_HOME_CODE
    ,TRY_TO_NUMBER(TEAMS_HOME_ID) as TEAMS_HOME_ID
    ,TEAMS_HOME_LOGO::VARCHAR as TEAMS_HOME_LOGO
    ,TEAMS_HOME_NAME::VARCHAR as TEAMS_HOME_NAME
    ,TEAMS_HOME_NICKNAME::VARCHAR as TEAMS_HOME_NICKNAME
    ,TEAMS_VISITORS_CODE::VARCHAR as TEAMS_VISITORS_CODE
    ,TEAMS_VISITORS_ID::NUMERIC as TEAMS_VISITORS_ID
    ,TEAMS_VISITORS_LOGO::VARCHAR as TEAMS_VISITORS_LOGO
    ,TEAMS_VISITORS_NAME::VARCHAR as TEAMS_VISITORS_NAME
    ,TEAMS_VISITORS_NICKNAME::VARCHAR as TEAMS_VISITORS_NICKNAME
    ,TRY_TO_NUMBER(TIMESTIED) as TIMESTIED
from raw.nba.games
