{{ config(
    materialized="table"
) }}

select 
    TRY_TO_NUMBER(GAME_ID) as GAME_ID
    ,TRY_TO_NUMBER(ID) as ID
    ,TRY_TO_NUMBER(STATISTICS_ASSISTS) as ASSISTS
    ,TRY_TO_NUMBER(STATISTICS_BIGGESTLEAD) as BIGGEST_LEAD
    ,TRY_TO_NUMBER(STATISTICS_BLOCKS) as BLOCKS
    ,TRY_TO_NUMBER(STATISTICS_DEFREB) as DEFENSIVE_REBOUND
    ,TRY_TO_NUMBER(STATISTICS_FASTBREAKPOINTS) as FASTBREAK_POINTS
    ,TO_DOUBLE(STATISTICS_FGA) as FIELD_GOAL_AVERAGE
    ,TRY_TO_NUMBER(STATISTICS_FGM) as FIELD_GOAL_MADE
    ,TO_DOUBLE(STATISTICS_FGP) as FIELD_GOAL_PERC
    ,TRY_TO_NUMBER(STATISTICS_FTA) as FREE_THROW_ATTEMPT
    ,TRY_TO_NUMBER(STATISTICS_FTM) as FREE_THROW_MADE
    ,TO_DOUBLE(STATISTICS_FTP) as FREE_THROW_PERC
    ,TRY_TO_NUMBER(STATISTICS_LONGESTRUN) as LONGEST_RUN
    ,TRY_TO_NUMBER(STATISTICS_OFFREB) as OFFENSIVE_REBOUND
    ,TRY_TO_NUMBER(STATISTICS_PFOULS) as PERSONAL_FOUL
    ,TRY_TO_NUMBER(STATISTICS_PLUSMINUS) as PLUS_MINUS
    ,TRY_TO_NUMBER(STATISTICS_POINTS) as POINTS
    ,TRY_TO_NUMBER(STATISTICS_POINTSINPAINT) as POINTS_IN_PAINT
    ,TRY_TO_NUMBER(STATISTICS_POINTSOFFTURNOVERS) as POINTS_OFF_TURNOVERS
    ,TRY_TO_NUMBER(STATISTICS_SECONDCHANCEPOINTS) as SECOND_CHANCE_POINTS
    ,TRY_TO_NUMBER(STATISTICS_STEALS) as STEALS
    ,TRY_TO_NUMBER(STATISTICS_TOTREB) as TOTREB
    ,TRY_TO_NUMBER(STATISTICS_TPA) as THREE_POINT_ATTEMPT
    ,TRY_TO_NUMBER(STATISTICS_TPM) as THREE_POINT_MADE
    ,TO_DOUBLE(STATISTICS_TPP) as THREE_POINT_PERC
    ,TRY_TO_NUMBER(STATISTICS_TURNOVERS) as TURNOVERS
    ,TRY_TO_TIMESTAMP(SYNC_TIME) as SYNC_TIME
    ,TEAM_CODE::VARCHAR as TEAM_CODE
    ,TRY_TO_NUMBER(TEAM_ID) as TEAM_ID
    ,TEAM_LOGO::VARCHAR as TEAM_LOGO
    ,TEAM_NAME::VARCHAR as TEAM_NAME
    ,TEAM_NICKNAME::VARCHAR as TEAM_NICKNAME
from raw.nba.games_statistics